[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git log -1 --pretty=%B | grep dependabot"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    skipBuildCache = true

[build.environment]
  NODE_VERSION = "22"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NEXT_WEBPACK_USEPOLLING = "1" 